---
# Template configuration files for podman

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ podman_templates_copy }}"
  when: podman_copy_templates
